#!/usr/bin/env python3
"""
Build data/devices-manifest.toml by reading every per-device TOML file under
data/devices/. Zola's load_data() can read a single file but can't enumerate a
directory, so the manifest gives templates a single place to iterate.

Each entry in the manifest gets an extra `slug` field (the filename stem) so
templates can link back to the source file on GitHub.

Run this BEFORE every Zola build. CI does this automatically; for local dev
just run it whenever you add or change a device.
"""

from __future__ import annotations

import sys
from pathlib import Path

import tomli

ROOT = Path(__file__).resolve().parent.parent
DEVICES_DIR = ROOT / "data" / "devices"
MANIFEST_PATH = ROOT / "data" / "devices-manifest.toml"

# Sort key — fully-supported devices first, then alphabetical.
STATUS_ORDER = {
    "fully-supported": 0,
    "partial": 1,
    "experimental": 2,
    "unsupported": 3,
}


def toml_escape(s: str) -> str:
    """Escape a string for inclusion in a TOML basic string."""
    return (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def emit_value(value) -> str:
    """Serialise a Python value to a TOML literal (just the types we use)."""
    if isinstance(value, str):
        return f'"{toml_escape(value)}"'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        items = ", ".join(emit_value(v) for v in value)
        return f"[{items}]"
    raise TypeError(f"Unsupported value type for manifest: {type(value).__name__}")


def main() -> int:
    if not DEVICES_DIR.is_dir():
        print(f"Error: {DEVICES_DIR} does not exist.", file=sys.stderr)
        return 1

    files = sorted(DEVICES_DIR.rglob("*.toml"))
    if not files:
        print("No device files found. Writing empty manifest.")
        MANIFEST_PATH.write_text(
            "# Auto-generated by scripts/build_manifest.py — do not edit by hand.\n"
            "devices = []\n",
            encoding="utf-8",
        )
        return 0

    devices: list[dict] = []
    for path in files:
        try:
            with path.open("rb") as f:
                data = tomli.load(f)
        except tomli.TOMLDecodeError as e:
            print(f"Error parsing {path.relative_to(ROOT)}: {e}", file=sys.stderr)
            return 1
        data["slug"] = path.stem
        devices.append(data)

    # Sort: status priority, then manufacturer, then name.
    devices.sort(
        key=lambda d: (
            STATUS_ORDER.get(d.get("status", ""), 99),
            d.get("manufacturer", "").lower(),
            d.get("name", "").lower(),
        )
    )

    # Emit TOML manually — array of inline tables keeps the file compact and
    # avoids pulling in a third-party TOML writer.
    lines = [
        "# Auto-generated by scripts/build_manifest.py — do not edit by hand.",
        "# Add devices by creating a new file under data/devices/<category>/.",
        "",
    ]
    for d in devices:
        lines.append("[[devices]]")
        # Stable field order for readable diffs (even though it's auto-generated).
        field_order = [
            "name",
            "manufacturer",
            "category",
            "status",
            "connectivity",
            "verified_version",
            "verified_date",
            "verified_by",
            "features",
            "notes",
            "manufacturer_url",
            "slug",
        ]
        # Emit known fields first in order, then any unexpected fields alphabetically.
        seen = set()
        for key in field_order:
            if key in d:
                lines.append(f"{key} = {emit_value(d[key])}")
                seen.add(key)
        for key in sorted(d.keys()):
            if key not in seen:
                lines.append(f"{key} = {emit_value(d[key])}")
        lines.append("")

    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {MANIFEST_PATH.relative_to(ROOT)} ({len(devices)} device(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
