#!/usr/bin/env python3
"""
generate-tables.py
Scans devices/ and regenerates the README.md table in each category folder.
Run: python scripts/generate-tables.py
"""

import os
import re
from pathlib import Path
from datetime import date

# ── Config ────────────────────────────────────────────────────────────────────

DEVICES_DIR = Path(__file__).parent.parent / "devices"

CATEGORY_META = {
    "heart-rate-monitors": {
        "emoji": "❤️",
        "title": "Heart Rate Monitors",
        "description": "ANT+ and Bluetooth LE heart rate monitors validated with the app.",
    },
    "foot-pods": {
        "emoji": "👟",
        "title": "Foot Pods",
        "description": "Foot pods for cadence and running dynamics.",
    },
    "bike-trainers": {
        "emoji": "🚴",
        "title": "Bike Trainers",
        "description": "Smart and classic bike trainers with power/speed support.",
    },
    "treadmills": {
        "emoji": "🏃",
        "title": "Treadmills",
        "description": "Treadmills with Bluetooth or ANT+ speed/incline data.",
    },
}

STATUS_BADGE = {
    "validated":       "✅ Validated",
    "community-tested": "🟡 Community",
    "untested":        "❓ Untested",
    "broken":          "❌ Broken",
}

# ── Frontmatter parser ────────────────────────────────────────────────────────

def parse_frontmatter(text: str) -> dict:
    """Extract YAML-style frontmatter from a markdown file (no external deps)."""
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}
    data = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        # Simple list parsing: [a, b, c]
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1]
            value = [v.strip().strip('"').strip("'") for v in inner.split(",") if v.strip()]
        else:
            value = value.strip('"').strip("'")
        data[key] = value
    return data


def parse_notes_section(text: str) -> str:
    """Pull first sentence of the ## Notes section if present."""
    match = re.search(r"##\s+Notes\s*\n+(.+)", text)
    if not match:
        return ""
    first = match.group(1).strip().split("\n")[0]
    # Truncate long notes
    return first[:80] + "…" if len(first) > 80 else first

# ── Table builder ─────────────────────────────────────────────────────────────

def build_table(devices: list[dict]) -> str:
    """Render a markdown table from a list of device dicts."""
    if not devices:
        return "_No devices listed yet. Be the first to [open a PR](../../CONTRIBUTING.md)!_\n"

    header = "| Brand | Model | Protocols | Status | Notes |\n"
    sep    = "|-------|-------|-----------|--------|-------|\n"
    rows   = ""
    for d in sorted(devices, key=lambda x: (x.get("brand", ""), x.get("name", ""))):
        brand     = d.get("brand", "—")
        name      = d.get("name", "—")
        protocols = d.get("protocols", [])
        if isinstance(protocols, list):
            protocols = ", ".join(protocols)
        status    = STATUS_BADGE.get(d.get("status", "untested"), "❓ Untested")
        notes     = d.get("_notes", "")
        rows += f"| {brand} | {name} | {protocols} | {status} | {notes} |\n"
    return header + sep + rows


def build_readme(category_dir: Path, meta: dict, devices: list[dict]) -> str:
    emoji = meta.get("emoji", "📋")
    title = meta.get("title", category_dir.name)
    desc  = meta.get("description", "")
    today = date.today().isoformat()
    table = build_table(devices)

    return f"""\
# {emoji} {title}

{desc}

> **{len(devices)} device(s) listed** · Last generated: {today}
>
> Don't see your device? [Open a PR](../../CONTRIBUTING.md) — it takes ~5 minutes!

## Supported Devices

{table}
## Status Legend

| Badge | Meaning |
|-------|---------|
| ✅ Validated | Tested by a maintainer on the latest stable release |
| 🟡 Community | Reported working by community members — not officially verified |
| ❓ Untested | Device likely works but has not been confirmed |
| ❌ Broken | Known issues; contributions welcome |

---
_This file is auto-generated by [`scripts/generate-tables.py`](../../scripts/generate-tables.py). Edit device `.md` files, not this table._
"""

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not DEVICES_DIR.exists():
        print(f"❌  devices/ directory not found at {DEVICES_DIR}")
        return

    categories_updated = 0

    for category_dir in sorted(DEVICES_DIR.iterdir()):
        if not category_dir.is_dir():
            continue

        category = category_dir.name
        meta = CATEGORY_META.get(category, {"emoji": "📋", "title": category.replace("-", " ").title(), "description": ""})
        devices = []

        # Walk all .md files (skip README.md itself)
        for md_file in sorted(category_dir.rglob("*.md")):
            if md_file.name.lower() == "readme.md":
                continue
            text = md_file.read_text(encoding="utf-8")
            fm = parse_frontmatter(text)
            if not fm:
                print(f"  ⚠️  No frontmatter in {md_file.relative_to(DEVICES_DIR)}, skipping.")
                continue
            fm["_notes"] = parse_notes_section(text)
            devices.append(fm)

        readme_content = build_readme(category_dir, meta, devices)
        readme_path = category_dir / "README.md"
        readme_path.write_text(readme_content, encoding="utf-8")

        print(f"✅  {category}: wrote {len(devices)} device(s) → {readme_path.relative_to(DEVICES_DIR.parent)}")
        categories_updated += 1

    print(f"\n🎉  Done — {categories_updated} category README(s) updated.")


if __name__ == "__main__":
    main()
